# used to provision initial items used to permit terraform/ansible components to create AWS infrastructure components
# also have been manually adding Administrator role to the account but is no longer required

Resources:
  terransibleuser:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: terransible_ec2_fullaccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - '*'
                Resource: '*'
      Tags:
        - Key: Usage
          Value: terransible lab
      UserName: terransibleuser
  terransibleuserkey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: terransibleuser
    DependsOn: terransibleuser
